### ISSUE TITLE
STM32U595/5A5/599/5A9 not being generated

### ISSUE THREAD

**Issue by tgree** [modm-io/modm-devices#102]
It looks like stm.py was set up to ignore STM32U59 and STM32U5A prefixes at some point.  We are considering using one of these due to their larger 4M flash sizes and I wanted to view their pinouts in my stm_layout_tk tool, so I updated modm-devices on my system but was surprised to see these ones missing.  I eventually found where they were being ignored and removed those lines, but then it errors out about missing memory models for the 599/5A9 series so I put those back on ignore.  I also noticed that these are listed as 85C parts and there wasn't an 85C entry in the temperature map.

This is my diff so far:
```
diff --git a/tools/generator/dfg/stm32/stm.py b/tools/generator/dfg/stm32/stm.py
index 362a04a..00ffb4c 100644
--- a/tools/generator/dfg/stm32/stm.py
+++ b/tools/generator/dfg/stm32/stm.py
@@ -8,8 +8,8 @@ LOGGER = logging.getLogger("dfg.stm.data")

 ignored_devices = \
 [
-    "STM32U59",
-    "STM32U5A",
+    "STM32U599",
+    "STM32U5A9",
     "STM32WL5M",
     "STM32WB1M",
     "STM32WB5M",
diff --git a/tools/generator/dfg/stm32/stm_device_tree.py b/tools/generator/dfg/stm32/stm_device_tree.py
index 7896252..2190680 100644
--- a/tools/generator/dfg/stm32/stm_device_tree.py
+++ b/tools/generator/dfg/stm32/stm_device_tree.py
@@ -26,7 +26,7 @@ class STMDeviceTree:
     """
     rootpath = os.path.join(os.path.dirname(__file__), "..", "..", "raw-device-data", "stm32-devices", "mcu")
     familyFile = XMLReader(os.path.join(rootpath, "families.xml"))
-    TemperatureMap = {0: "6", 105: "7", 125: "3"}
+    TemperatureMap = {0: "6", 85: "6", 105: "7", 125: "3"}

     @staticmethod
     def _format_raw_devices(rawDevices):
```

I'm not sure why those MCUs were originally put on ignore, so maybe there's some other reason to blacklist them?  I can also try and sort out the missing memory models if you like.

**Comment by rleh** [comment]
The STM32U5{95, 99, A5, A9} chips were not officially launched a year ago when adding STM32U5 support to modm-devices and there were no datasheets available
(https://github.com/modm-io/modm-devices/pull/82#discussion_r841297589).
Feel free to remove them from the ignore list and add the memory data!
Let us know if you need further help.
