### ISSUE TITLE
Actions are broken?

### ISSUE THREAD

**Issue by salkinium** [modm-io/modm-devices#95]
Neither the PR event nor the regular scheduled CI Actions is running.

Completely unclear why? Perhaps something was deprecated.

**Comment by chris-durand** [comment]
They are working again after you have merged your last PR with updating the deprecated actions. It seems you have to merge the changes to the action files for github to apply them. I have pushed to PR #83 for testing purposes and the actions are running.

**Comment by salkinium** [comment]
Oh, right. I accidentally did the right thing then ;-P
